spring.application.name=taskplanner

# H2 Database Config
spring.datasource.url=jdbc:h2:file:/Users/tridharamamilla/Documents/PersonalProjects/taskplanner/data/taskplannerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false


# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
logging.level.org.hibernate=DEBUG

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console